export interface ProjectBrief { selected:boolean; evidence:string; contribution:string; method:string; outcome:string; cardRole:string; cardResult:string; links?:{label:string;href:string}[] }
export const projectBriefs:Record<string,ProjectBrief>={
 'sard-drone':{selected:true,evidence:'Physical prototype · bench demonstrations',contribution:'Independent project: component selection, wiring, Python vision and sensing software, and a custom 3D-printed camera mount.',method:'Integrated flight control, sensor acquisition, and onboard vision. Added rubber dampers to address camera jitter and worked on stabilization tuning.',outcome:'Built and demonstrated the hardware and vision interface. Damping had limited effectiveness; camera jitter, long-range detection, and stabilization remained technical challenges.',cardRole:'Independent hardware & software integration',cardResult:'Working bench demonstrations; documented vibration and detection limitations.',links:[{label:'Project repository',href:'https://github.com/Aryaa207/sard-assets'},{label:'Sensor acquisition code',href:'https://github.com/Aryaa207/sard-assets/blob/main/AppV6.py'},{label:'Vision implementation',href:'https://github.com/Aryaa207/sard-assets/blob/main/Detection_v7.py'}]},
 'pn-guidance':{selected:true,evidence:'Classroom simulation · 200-trial comparison',contribution:'Primary contributor to MATLAB implementation and analysis. The final presentation credits a three-person team.',method:'Compared True PN and Augmented PN using a deterministic example and a randomized 200-trial ensemble, with original trajectory and acceleration plots.',outcome:'The reported ensemble has similar mean miss distances and different acceleration demands. Results apply to the classroom model; formal statistical equivalence is not established.',cardRole:'Primary implementation & analysis contributor',cardResult:'200-trial comparison with original trajectories, acceleration histories, and results table.'},
 'mach5-hypersonic-cfd':{selected:true,evidence:'CFD setup · original contour exports',contribution:'Prepared geometry, generated the computational mesh, and analyzed external flow in ANSYS Fluent.',method:'Mach 5 ideal-gas flow with SST k–ω turbulence and a density-based implicit solver; the documented mesh contains 3,389,998 tetrahedral cells.',outcome:'Produced Mach and pressure contour exports. The available records do not establish a final converged drag coefficient or validated heating prediction.',cardRole:'Geometry preparation, meshing & CFD analysis',cardResult:'Documented solver setup and original flow fields, with convergence limits stated.'},
 'flying-wing-glider':{selected:false,evidence:'Team design & fabrication project',contribution:'Project manager for four people. Led airfoil selection, Reynolds-number estimation, and glide-ratio prediction; created NX CAD and technical drawings.',method:'Coordinated the progression from aerodynamic estimates to fabrication and flight testing.',outcome:'Completed the team design-to-test workflow. Numerical flight measurements are not included in the current case study.',cardRole:'Project manager · team of four',cardResult:'Aerodynamic estimates, NX drawings, fabrication, and flight testing.'},
 'interceptor-capstone':{selected:false,evidence:'Senior capstone · in progress',contribution:'Controls / GNC lead on a senior capstone team.',method:'Current work concerns controls and systems integration; detailed team milestones are not yet part of this portfolio.',outcome:'In progress. No completed system performance is claimed.',cardRole:'Controls / GNC lead',cardResult:'Current senior capstone; results to follow completed verification.'},
 'kia-k4-cfd':{selected:false,evidence:'Geometry archive',contribution:'Archived external-aerodynamics study. This page currently presents the supplied surface geometry.',method:'Interactive inspection of the vehicle geometry and recovered surface rendering.',outcome:'Geometry reference only in the available archive; solver setup and numerical results are not established here.',cardRole:'External-aerodynamics study archive',cardResult:'Surface geometry viewer; not presented as validated CFD evidence.'},
 'cal50-projectile-cfd':{selected:false,evidence:'CFD study · partially converged record',contribution:'External-flow analysis in ANSYS Fluent, with the original saved report and contour exports.',method:'Mach 2.7 calculation; the saved report documents 1,804,197 cells and 950 iterations.',outcome:'Contours and monitor histories are available. Several residuals remain unconverged, so coefficients are presented as saved-run values.',cardRole:'CFD study',cardResult:'Original residuals, monitors, and flow fields with convergence scope.'},
 'sr-71-geometry':{selected:false,evidence:'Geometry reference · visualization only',contribution:'Surface-model exploration presented through an interactive viewer; no original aircraft design or model authorship claim.',method:'Orbit, wireframe, and section-plane inspection of the supplied geometry.',outcome:'A reference visualization, not a simulation or validated aerodynamic result.',cardRole:'Geometry reference',cardResult:'Interactive surface model, separate from the selected engineering case studies.'},
};
