export const sardComponents = [
  { name:'Arducam 64 MP', group:'01 / Primary vision', image:'arducam64mp', spec:'64 MP · autofocus camera', text:'High-resolution camera payload mounted on the custom pan–tilt assembly.', note:'Camera module and housing', position:[.15,.16,.18] },
  { name:'OV2659 camera', group:'02 / Secondary vision', image:'ov2659', spec:'2 MP · secondary camera', text:'Secondary imaging module in the vision hardware archive.', note:'Repository component photograph', position:[-.18,.15,.12] },
  { name:'NEO-6M GPS', group:'03 / Position sensing', image:'neo6m', spec:'GPS receiver · ceramic antenna', text:'Position receiver included in the sensing package, with a separate antenna.', note:'Receiver board and antenna', position:[0,.12,-.16] },
  { name:'LSM9DS1 IMU', group:'04 / Inertial sensing', image:'lsm9ds1', spec:'Accelerometer · gyroscope · magnetometer', text:'Inertial sensor used for acquisition and attitude visualization. Open the IMU tab for the bench workflow.', note:'Nine-axis inertial sensor module', position:[-.12,.06,0] },
  { name:'Arduino controller', group:'05 / Sensor interface', image:'arduinonano', spec:'Arduino Nano specified in project poster', text:'Microcontroller interface for the sensing hardware. The repository image shows an Uno board as a reference.', note:'Uno reference image; project specifies Nano', position:[.13,.02,-.08] },
  { name:'Raspberry Pi 4B', group:'06 / Onboard compute', image:'rpi4b', spec:'Python · OpenCV · sensor acquisition', text:'Runs the vision software. The separate IMU bench application acquires LSM9DS1 data directly over I²C.', note:'Single-board computer', position:[-.06,-.01,.10] },
  { name:'KK2.1.5 controller', group:'07 / Flight control', image:'kk215', spec:'Dedicated stabilization controller', text:'Flight-control board, separate from the Raspberry Pi vision and sensor visualization software.', note:'Flight-control board', position:[0,-.05,0] },
  { name:'3S LiPo battery', group:'08 / Electrical power', image:'lipo3s', spec:'Three-cell lithium-polymer supply', text:'Battery hardware from the project component archive. The image shows two packs; it is not a flight-mass measurement.', note:'Battery packs from component archive', position:[0,-.13,0] },
];
